<?php

namespace common\models\forms;


use kartik\growl\Growl;
use Yii;
use yii\base\Model;

class CreateDocForm extends Model
{

    public $category;
    public $sub_category;
    public $group_doc;
    public $main_doc;
    public $type_doc;


    public function rules()
    {
        return [
            [['barcode'], 'string'],
            [['card_number', 'order_id', 'element_id'], 'integer'],
            [['group_doc', 'sub_category', 'category','main_doc','type_doc'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }


}