<?php

namespace common\models\forms;

use Yii;
use yii\base\Model;

class UserForm extends Model
{

    public $login;
    public $old_pass;
    public $new_pass;
    public $new_pass_confirm;
    public $email;


    public function rules()
    {
        return [
            [['login', 'old_pass', 'new_pass', 'new_pass_confirm', 'email'], 'string'],
            [['login', 'old_pass', 'new_pass', 'new_pass_confirm', 'email'], 'required']

        ]; // TODO: Change the autogenerated stub
    }

    public function changeUserPassword()
    {
        $user = Yii::$app->user->identity;

//        $user = $this->_user;
//            dd($this->new_pass);
        $check = $user->validatePassword($this->old_pass);

        if (!$check) {
            Yii::$app->session->addFlash('error', 'old password error');
            return false;
        }

        if ($this->new_pass == $this->new_pass_confirm) {
            $user->setPassword($this->new_pass_confirm);
            $user->removePasswordResetToken();
            $user->generateAuthKey();
            if (!$user->save()) {
                Yii::$app->session->addFlash('error', 'not');

            } else {
                Yii::$app->session->addFlash('success', 'Changed');
                return true;
            }

        } else {
            Yii::$app->session->addFlash('error', 'xato');
        }
        return true;
//        $user->setPassword($this->new_pass);
//        $user->removePasswordResetToken();
//        $user->generateAuthKey();

//        if (!$user->save()) {
//            dd($user->errors);
//        } else {
//            Yii::$app->session->addFlash('success', 'Changed');
//            return true;
//        }
    }


}